name: build-and-archive-angular-app
on: [push]
jobs:
  build-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v2"
              - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Setup Node-Environment
        uses: "actions/setup-node@v2"
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Start Appium Inspector
        run: |
          npm install -g appium
          appium &

      - name: Run tests
        run: npm test